---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-appdaemon3"
  ADDON_SLUG: "appdaemon3"
  ADDON_TARGET: "appdaemon"

  ADDON_ARMV7: "false"
  ADDON_LEGACY_TAGS: "true"

  ADDON_AARCH64_BASE: "hassioaddons/base-aarch64:3.0.1"
  ADDON_AMD64_BASE: "hassioaddons/base-amd64:3.0.1"
  ADDON_ARMHF_BASE: "hassioaddons/base-armhf:3.0.1"
  ADDON_I386_BASE: "hassioaddons/base-i386:3.0.1"
